[package]
name = "geo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
zela-std.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
